spring.application.name=budget-tracker-api

# Temporary for setup(1): database configuration will be handled in setup(2)
spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration