spring.application.name=budget-tracker-api

spring.datasource.url=jdbc:postgresql://localhost:5432/budget_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres

# autorise Hibernate à adapter la base en dev.
spring.jpa.hibernate.ddl-auto=update
# Utile pour comprendre ce que JPA fait réellement derrière tes repositories.
spring.jpa.show-sql=true
# Rend ces requêtes SQL plus lisibles, avec indentation et retours à la ligne.
spring.jpa.properties.hibernate.format_sql=true
